apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: beappstaging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: beappstaging
        tier: backend
    spec:
      containers:
      - name: beapp
        image: vinodkottem/beapp:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REDIS_URI
          value: redis.default.svc.cluster.local:6379
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 3000
